### ISSUE TITLE
사용중에 간헐적으로 프로그램이 꺼집니다.

### ISSUE THREAD

**Issue by ghost** [sappho192/Amaurot-Translator#1]
안녕하세요! 만들어주신 프로그램 잘쓰고 있습니다!

다름이 아니라 이번에 크롬 업뎃후에 실행이 되질 않아 자체적으로 크롬 드라이버를 씌워서 사용하고 있었는데 두가지 방식으로 먹통이 되고 튕깁니다.

하나는 검은 화면의 크롬창이 뜨고 계속 꺼도 꺼도 창이 나타나며, 하나는 그냥 멈추다가 혼자 꺼집니다.

창이 뜨는 경우에는 일단 작업관리자에서 모든 크롬 관련 프로그램을 끄면 해결이 됩니다만... 로그나 이런게 남은게 없어서... 여튼 이러한 버그 증상이 있는데 원인을 모르겠네요.

나중에 한가하실때 봐주시면 감사할 것 같습니다 :)

**Comment by sappho192** [comment]
@souleda22 님 안녕하세요, 이슈로 와주셔서 해당 내용 제보해주셔서 감사합니다.
해당 내용은 저도 이제 막 확인하였으며, 기말고사가 끝나는 대로 반영하도록 하겠습니다.

**Comment by sappho192** [comment]
@souleda22 님 안녕하세요, https://github.com/sappho192/AmaurotTranslator/releases/tag/0.0.4 에서 크롬 91 드라이버가 반영된 프로그램을 받으실 수 있습니다. 
일단 현재의 해결방법은 크롬 버전이 올라갈때마다 빌드를 새로 해야해서 굉장히 귀찮은 면이 있으므로 다음 버전부터는 앱에서 크롬 드라이버를 자동 업데이트 할 수 있도록 해보겠습니다.

(https://sqa.stackexchange.com/questions/41928/how-to-autoupdate-chrome-driver-in-selenium 참조)

**Comment by sappho192** [comment]
@souleda22 안녕하세요, 최신 [0.0.6](https://github.com/sappho192/AmaurotTranslator/releases/tag/0.0.6) 버전에 로그를 남기는 기능을 추가하였습니다.
추후에 또 프로그램이 말없이 꺼진다면 로그 파일을 여기에 첨부해주시면 제가 조사해보도록 하겠습니다. 감사합니다.
